### ISSUE TITLE
BLPImage: alphaBits is 9 (expected 0, 1, 4 or 8), defaulting to 0.

### ISSUE THREAD

**Issue by linslin** [triggerhappy187/PHP-BLP#2]
While convert this (https://www.dropbox.com/s/mv7f6hg7kevmyei/LoadingScreen.blp?dl=0) BLP file we get the following exception: 

`BLPImage: alphaBits is 9 (expected 0, 1, 4 or 8), defaulting to 0.` 

I dont know how to fix this. Any help would be appreciated.

**Comment by cipherxof** [comment]
It's only a warning, you can ignore it. As far as I know 9 is not a valid value for the alphaBits field, so it defaults to 0.

I tested this myself and the image still converts successfully.
